FORMAT: 1A

# OpenBook API

## Group Tables

### GET /tables 

+ Response 200 (application/json)

        [
            "Chapters",
            "Donations",
            "Expenses",
            "Members",
            "Projects"
        ]

### GET /tables/:table 

+ Parameters

    + table: Members

+ Response 200 (application/json)

        [
            "BDisp.md",
            "Brian G.md",
            "Charles Shisler.md",
            "Hannah Mulein.md",
            "Jessica Mulein.md",
            "Jon.md",
            "Joseph Arceneaux.md",
            "Rui Campos.md",
            "Vijayee.md",
            "template.md"
        ]

### GET /tables/:table/data 

+ Parameters

    + table: Members

+ Response 200 (application/json)

        [
            {
                "type": "root",
                "children": [
                ...
                ],
                "position": {
                    "start": {
                        "line": 1,
                        "column": 1,
                        "offset": 0
                    },
                    "end": {
                        "line": 9,
                        "column": 1,
                        "offset": 283
                    }
                }
            }
        ]

### GET /tables/:table_name/files/:file_name 

+ Parameters

    + table_name: Members
    + file_name: Jessica Mulein.md

+ Response 200 (application/json)

        [
            "markdown",
            "html",
            "json"
        ]

### GET /tables/:table_name/files/:file_name/json 

+ Parameters

    + table_name: Members
    + file_name: Jessica Mulein.md

+ Response 200 (application/json)

        {
            "type": "root",
            "children": [
            ...
            ],
            "position": {
                "start": {
                    "line": 1,
                    "column": 1,
                    "offset": 0
                },
                "end": {
                    "line": 14,
                    "column": 1,
                    "offset": 472
                }
            }
        }

### GET /tables/:table_name/files/:file_name/html 

+ Parameters

    + table_name: Members
    + file_name: Jessica Mulein.md

+ Response 200 (application/html)

        <h1>Donation</h1>
        <p><strong>Name:</strong> Donation to cover Charitable Organization Registration
        ...

### GET /tables/:table_name/files/:file_name/markdown 

+ Parameters

    + table_name: Members
    + file_name: Jessica Mulein.md

+ Response 200 (application/markdown)

        # Donation

        **Name:** Donation to cover Charitable Organization Registration
        ...

## Group Views

### GET /view/:table_name 

+ Parameters

    + table_name: Members

+ Response 200 (application/json)

        {
            ...
            "Jessica Mulein.md": {
                "Name": "Jessica Mulein",
                ...
            },
            ...
        }

### GET /view/:table_name/paths 

+ Parameters

    + table_name: Members

+ Response 200 (application/json)

        [
            "root.0.heading.0.text",
            ...
        ]

### GET /view/:table_name/paths/:path 

+ Parameters

    + table_name: Members
    + path: root.0.heading.0.text

+ Response 200 (application/json)

        [
            ...
            {
                "file": "Jessica Mulein.md",
                "value": "Jessica Mulein"
            },
            ...
        ]

### GET /view/:table_name/condensed 

+ Parameters

    + table_name: Members

+ Response 200 (application/json)

        [
            [
                "Name",
                ...
            ],
            ...
        ]

### GET /view/:table_name/excel 

+ Parameters

    + table_name: Members

+ Response 200 (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)